"""
blueprint.py — Feature selection blueprint and feature score models for KiteML.
"""

from dataclasses import asdict, dataclass, field
from typing import Any

from kiteml.feature_selection.strategy import SelectionDecision


@dataclass
class FeatureScore:
    """
    Evaluation score and selection decision for a single feature.
    """

    feature_name: str
    score: float  # 0.0 to 100.0
    confidence: float = 0.90  # 0.0 to 1.0
    decision: SelectionDecision | str = SelectionDecision.KEEP
    reasoning: list[str] = field(default_factory=list)
    selector_votes: dict[str, str] = field(default_factory=dict)
    is_protected: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Serialize FeatureScore to dictionary."""
        d = asdict(self)
        dec = self.decision
        d["decision"] = dec.value if hasattr(dec, "value") else str(dec)
        return d


@dataclass
class FeatureSelectionBlueprint:
    """
    Complete dataset feature selection blueprint generated by FeatureSelectionEngine.
    """

    selected_features: list[str] = field(default_factory=list)
    removed_features: list[str] = field(default_factory=list)
    protected_features: list[str] = field(default_factory=list)
    feature_scores: dict[str, FeatureScore] = field(default_factory=dict)
    target_name: str | None = None
    problem_type: str | None = None
    warnings: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)

    @property
    def total_features(self) -> int:
        """Total number of evaluated features."""
        return len(self.feature_scores)

    def summary_text(self, width: int = 55) -> str:
        """Render human-readable summary box of feature selection decisions."""
        lines = [
            "═" * width,
            "🎯 KiteML Feature Selection Blueprint",
            "═" * width,
            f"  Target Column          {self.target_name or 'N/A'}",
            f"  Total Features         {self.total_features}",
            f"  Selected (Keep)        {len(self.selected_features)}",
            f"  Removed (Drop)         {len(self.removed_features)}",
            f"  Protected Features     {len(self.protected_features)}",
            "─" * width,
        ]

        for feat_name, score_obj in self.feature_scores.items():
            dec = score_obj.decision.value if hasattr(score_obj.decision, "value") else str(score_obj.decision)
            if dec == "keep":
                prot_str = " (Protected)" if score_obj.is_protected else ""
                lines.append(f"  ✓ {feat_name:<24} [Score: {score_obj.score:5.1f}] KEEP{prot_str}")
            elif dec == "remove":
                lines.append(f"  ❌ {feat_name:<24} [Score: {score_obj.score:5.1f}] REMOVE")
                if score_obj.reasoning:
                    lines.append(f"     → Reason: {score_obj.reasoning[0]}")
            else:
                lines.append(f"  ⚠ {feat_name:<24} [Score: {score_obj.score:5.1f}] {dec.upper()}")

        lines.append("═" * width)
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """Serialize blueprint to dictionary."""
        return {
            "target_name": self.target_name,
            "problem_type": self.problem_type,
            "total_features": self.total_features,
            "selected_features": self.selected_features,
            "removed_features": self.removed_features,
            "protected_features": self.protected_features,
            "feature_scores": {f: s.to_dict() for f, s in self.feature_scores.items()},
            "warnings": self.warnings,
            "suggestions": self.suggestions,
        }
