"""
blueprint.py — Preprocessing blueprint and feature execution plan models for KiteML.
"""

from dataclasses import asdict, dataclass, field
from typing import Any

from kiteml.preprocessing.strategy import (
    DatetimeStrategy,
    EncodingStrategy,
    MissingStrategy,
    ScalingStrategy,
    TextStrategy,
)


@dataclass
class FeaturePlan:
    """
    Preprocessing execution plan for a single dataset feature.
    """

    feature_name: str
    datatype: str
    missing_strategy: MissingStrategy | str = MissingStrategy.NONE
    encoding_strategy: EncodingStrategy | str = EncodingStrategy.NONE
    scaling_strategy: ScalingStrategy | str = ScalingStrategy.NONE
    datetime_strategy: DatetimeStrategy | str = DatetimeStrategy.NONE
    text_strategy: TextStrategy | str = TextStrategy.NONE
    ignore: bool = False
    confidence: float = 1.0
    reasoning: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize FeaturePlan to dictionary."""
        d = asdict(self)
        for key in ("missing_strategy", "encoding_strategy", "scaling_strategy", "datetime_strategy", "text_strategy"):
            val = getattr(self, key)
            d[key] = val.value if hasattr(val, "value") else str(val)
        return d


@dataclass
class PreprocessingBlueprint:
    """
    Complete dataset preprocessing blueprint generated by PreprocessingEngine.
    """

    feature_plans: dict[str, FeaturePlan] = field(default_factory=dict)
    global_settings: dict[str, Any] = field(default_factory=dict)
    target_name: str | None = None
    problem_type: str | None = None
    warnings: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)

    @property
    def feature_count(self) -> int:
        """Total number of feature plans."""
        return len(self.feature_plans)

    @property
    def active_features(self) -> list[str]:
        """List of feature names not marked for ignore."""
        return [f for f, p in self.feature_plans.items() if not p.ignore]

    @property
    def ignored_features(self) -> list[str]:
        """List of feature names marked for ignore."""
        return [f for f, p in self.feature_plans.items() if p.ignore]

    def summary_text(self, width: int = 50) -> str:
        """Render human-readable summary box of the preprocessing blueprint."""
        lines = [
            "═" * width,
            "📋 KiteML Preprocessing Blueprint",
            "═" * width,
            f"  Target Column        {self.target_name or 'N/A'}",
            f"  Problem Type         {self.problem_type or 'N/A'}",
            f"  Total Features       {self.feature_count}",
            f"  Active Features      {len(self.active_features)}",
            f"  Ignored Features     {len(self.ignored_features)}",
            "─" * width,
        ]

        for feat_name, plan in self.feature_plans.items():
            if plan.ignore:
                lines.append(f"  ❌ {feat_name:<20} [IGNORED]")
                if plan.reasoning:
                    lines.append(f"     → Reason: {plan.reasoning[0]}")
            else:
                strats = []
                if plan.missing_strategy != MissingStrategy.NONE:
                    strats.append(f"Impute: {plan.missing_strategy}")
                if plan.encoding_strategy != EncodingStrategy.NONE:
                    strats.append(f"Encode: {plan.encoding_strategy}")
                if plan.scaling_strategy != ScalingStrategy.NONE:
                    strats.append(f"Scale: {plan.scaling_strategy}")
                if plan.datetime_strategy != DatetimeStrategy.NONE:
                    strats.append(f"Date: {plan.datetime_strategy}")
                if plan.text_strategy != TextStrategy.NONE:
                    strats.append(f"Text: {plan.text_strategy}")

                strat_desc = ", ".join(strats) if strats else "Pass-through"
                lines.append(f"  ✓ {feat_name:<20} ({plan.datatype})")
                lines.append(f"     → {strat_desc}")

        lines.append("═" * width)
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """Serialize blueprint to dictionary."""
        return {
            "target_name": self.target_name,
            "problem_type": self.problem_type,
            "feature_count": self.feature_count,
            "active_features": self.active_features,
            "ignored_features": self.ignored_features,
            "feature_plans": {f: p.to_dict() for f, p in self.feature_plans.items()},
            "global_settings": self.global_settings,
            "warnings": self.warnings,
            "suggestions": self.suggestions,
        }
