"""
transformation_pipeline.py — TransformationPipeline orchestrator for KiteML.
"""

import time
from typing import Any, Sequence

import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin

from kiteml.feature_engineering.planner import FeatureEngineeringEngine
from kiteml.feature_selection.planner import FeatureSelectionEngine
from kiteml.pipeline.context import PipelineContext
from kiteml.pipeline.dag import PipelineDAG
from kiteml.pipeline.stages import (
    DatetimeStage,
    EncodingStage,
    FeatureEngineeringStage,
    FeatureSelectionStage,
    MissingValueStage,
    PipelineStage,
    ScalingStage,
)
from kiteml.pipeline.state import PipelineState
from kiteml.pipeline.validator import PipelineValidator
from kiteml.preprocessing.planner import PreprocessingEngine


class TransformationPipeline(BaseEstimator, TransformerMixin):
    """
    Intelligent Transformation Pipeline.

    Executes preprocessing, feature engineering, and feature selection blueprints
    generated by Stories 4.1–4.3, converting raw datasets into model-ready datasets.
    """

    def __init__(
        self,
        preprocessing_blueprint: Any | None = None,
        engineering_blueprint: Any | None = None,
        selection_blueprint: Any | None = None,
        stages: Sequence[PipelineStage] | None = None,
    ) -> None:
        self.preprocessing_blueprint = preprocessing_blueprint
        self.engineering_blueprint = engineering_blueprint
        self.selection_blueprint = selection_blueprint
        self._custom_stages = list(stages) if stages else None

        self.dag = PipelineDAG()
        self.context = PipelineContext(
            preprocessing_blueprint=self.preprocessing_blueprint,
            engineering_blueprint=self.engineering_blueprint,
            selection_blueprint=self.selection_blueprint,
        )
        self.state = PipelineState()
        self.validator = PipelineValidator()
        self.fitted_stages: list[PipelineStage] = []
        self._is_fitted: bool = False
        from kiteml.reporting.timeline import TransformationTimeline

        self.timeline = TransformationTimeline()

    def _default_stages(self) -> list[PipelineStage]:
        """Return standard ordered suite of transformation stages."""
        return [
            MissingValueStage(),
            DatetimeStage(),
            EncodingStage(),
            ScalingStage(),
            FeatureEngineeringStage(),
            FeatureSelectionStage(),
        ]

    def fit(
        self,
        X: pd.DataFrame,
        y: Any = None,
        target: str | None = None,
        problem_type: str | None = None,
        keep_features: Sequence[str] | None = None,
    ) -> "TransformationPipeline":
        """
        Fit the transformation pipeline on input dataset X.

        Parameters
        ----------
        X : pd.DataFrame
            Raw training DataFrame.
        y : Any, optional
            Target values array.
        target : str, optional
            Target feature name.
        problem_type : str, optional
            Task type ('classification' or 'regression').
        keep_features : Sequence[str], optional
            Protected features to preserve during selection.

        Returns
        -------
        TransformationPipeline
            Fitted pipeline instance.
        """
        start_time = time.time()
        self.context.original_df = X.copy()
        self.context.target_name = target
        self.context.problem_type = problem_type

        # 1. Automatically generate plans if blueprints are not pre-computed
        if not self.preprocessing_blueprint:
            prep_engine = PreprocessingEngine()
            self.preprocessing_blueprint = prep_engine.plan(X, target=target, problem_type=problem_type)
            self.context.preprocessing_blueprint = self.preprocessing_blueprint

        if not self.engineering_blueprint:
            fe_engine = FeatureEngineeringEngine()
            self.engineering_blueprint = fe_engine.plan(
                X,
                preprocessing_blueprint=self.preprocessing_blueprint,
                target=target,
                problem_type=problem_type,
            )
            self.context.engineering_blueprint = self.engineering_blueprint

        if not self.selection_blueprint:
            fs_engine = FeatureSelectionEngine()
            self.selection_blueprint = fs_engine.plan(
                X,
                preprocessing_blueprint=self.preprocessing_blueprint,
                feature_engineering_blueprint=self.engineering_blueprint,
                target=target,
                problem_type=problem_type,
                keep_features=keep_features,
            )
            self.context.selection_blueprint = self.selection_blueprint

        # 2. Validate blueprint consistency
        valid, errs = self.validator.validate_blueprints(
            self.preprocessing_blueprint,
            self.engineering_blueprint,
            self.selection_blueprint,
        )
        if not valid:
            self.context.warnings.extend(errs)

        # 3. Setup DAG
        stage_list = self._custom_stages or self._default_stages()
        self.dag = PipelineDAG()
        for stage in stage_list:
            self.dag.add_stage(stage)

        ordered_stages = self.dag.topological_sort()
        self.fitted_stages = []

        # 4. Sequentially fit and transform DataFrame across stages
        curr_df = X.copy()
        if target and target in curr_df.columns:
            curr_df = curr_df.drop(columns=[target])

        for stage in ordered_stages:
            stage_name = stage.name
            self.state.current_stage = stage_name
            t0 = time.time()
            in_shape = (len(curr_df), len(curr_df.columns))

            try:
                stage.fit(curr_df, y=y, context=self.context)
                curr_df = stage.transform(curr_df, context=self.context)
                out_shape = (len(curr_df), len(curr_df.columns))
                dur_ms = (time.time() - t0) * 1000.0

                from kiteml.reporting.timeline import ReplayEvent

                self.timeline.add_event(
                    ReplayEvent(
                        stage_name=stage_name,
                        duration_ms=dur_ms,
                        input_shape=in_shape,
                        output_shape=out_shape,
                    )
                )

                self.fitted_stages.append(stage)
                self.state.mark_completed(stage_name)
            except Exception as e:
                self.state.mark_failed(stage_name)
                self.context.warnings.append(f"Stage '{stage_name}' failed: {e}")
                raise e

        self.context.current_df = curr_df
        self.state.execution_time = time.time() - start_time
        self._is_fitted = True
        return self

    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Transform dataset X using fitted pipeline stages.

        Parameters
        ----------
        X : pd.DataFrame
            Input DataFrame.

        Returns
        -------
        pd.DataFrame
            Model-ready transformed DataFrame.
        """
        if not self._is_fitted:
            raise RuntimeError("TransformationPipeline is not fitted yet. Call fit() before transform().")

        curr_df = X.copy()
        target = self.context.target_name
        if target and target in curr_df.columns:
            curr_df = curr_df.drop(columns=[target])

        for stage in self.fitted_stages:
            curr_df = stage.transform(curr_df, context=self.context)

        return curr_df

    def fit_transform(
        self,
        X: pd.DataFrame,
        y: Any = None,
        target: str | None = None,
        problem_type: str | None = None,
        keep_features: Sequence[str] | None = None,
    ) -> pd.DataFrame:
        """Fit pipeline and return transformed dataset."""
        return self.fit(X, y=y, target=target, problem_type=problem_type, keep_features=keep_features).transform(X)

    def report(self) -> Any:
        """Generate a comprehensive PipelineReport for this pipeline."""
        from kiteml.reporting.builder import ReportBuilder

        return ReportBuilder().build_report(self)

    def save(self, filepath: Any) -> str:
        """Save fitted pipeline to a .kml package file."""
        from kiteml.serialization.engine import save_pipeline

        return save_pipeline(self, filepath)

    @classmethod
    def load(cls, filepath: Any) -> "TransformationPipeline":
        """Load fitted pipeline from a .kml package file."""
        from kiteml.serialization.engine import load_pipeline

        return load_pipeline(filepath)
