"""
api_generator.py — Generate FastAPI application source code from a KiteML Result.

Produces ready-to-deploy Python source files, no FastAPI installation needed
to generate the code.
"""

import json
import os
import time
from typing import Any, Dict, List, Optional


_APP_TEMPLATE = '''\
"""
kiteml_api.py — Auto-generated KiteML inference API
Model    : {model_name}
Type     : {problem_type}
Generated: {generated_at}
"""

import json
import os
import time
from typing import Any, Dict, List, Optional

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ── Configuration ──────────────────────────────────────────────────────────────
MODEL_NAME = {model_name_repr}
PROBLEM_TYPE = {problem_type_repr}
FEATURE_NAMES = {feature_names_repr}
BUNDLE_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Load model and preprocessor ───────────────────────────────────────────────
model = joblib.load(os.path.join(BUNDLE_DIR, "model.joblib"))
_prep_path = os.path.join(BUNDLE_DIR, "preprocessor.joblib")
preprocessor = joblib.load(_prep_path) if os.path.exists(_prep_path) else None

_START = time.time()
_COUNTER = 0

# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title=f"KiteML — {{MODEL_NAME}}",
    description="Auto-generated by KiteML. Powered by scikit-learn.",
    version="1.0.0",
)
app.add_middleware(CORSMiddleware, allow_origins=["*"],
                   allow_methods=["*"], allow_headers=["*"])

# ── Request / Response schemas ─────────────────────────────────────────────────
class PredictRequest(BaseModel):
    data: List[Dict[str, Any]]
    return_probabilities: bool = True

class PredictResponse(BaseModel):
    predictions: List[Any]
    probabilities: Optional[List[Dict[str, float]]] = None
    n_rows: int
    model: str
    latency_ms: float

# ── Endpoints ──────────────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return {{"status": "healthy", "uptime_s": round(time.time() - _START, 1)}}

@app.get("/version")
def version():
    return {{"model": MODEL_NAME, "problem_type": PROBLEM_TYPE,
            "n_features": len(FEATURE_NAMES)}}

@app.get("/schema")
def schema():
    return {{"required_features": FEATURE_NAMES, "problem_type": PROBLEM_TYPE}}

@app.get("/metrics")
def metrics():
    global _COUNTER
    return {{"predictions_total": _COUNTER, "uptime_s": round(time.time() - _START, 1)}}

@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    global _COUNTER
    t0 = time.perf_counter()
    try:
        df = pd.DataFrame(request.data)
        present = [f for f in FEATURE_NAMES if f in df.columns]
        if not present:
            raise HTTPException(400, "No matching feature columns found in input.")
        df = df[present]
        X = preprocessor.transform(df) if preprocessor else df.values
        preds = model.predict(X).tolist()
        probas = None
        if request.return_probabilities and hasattr(model, "predict_proba"):
            raw = model.predict_proba(X)
            classes = [str(c) for c in getattr(model, "classes_", range(raw.shape[1]))]
            probas = [dict(zip(classes, row.tolist())) for row in raw]
        _COUNTER += len(preds)
        return PredictResponse(predictions=preds, probabilities=probas,
                               n_rows=len(preds), model=MODEL_NAME,
                               latency_ms=round((time.perf_counter()-t0)*1000, 2))
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference error: {{e}}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''


def generate_api(
    result: Any,
    output_dir: str = ".",
    filename: str = "kiteml_api.py",
) -> str:
    """
    Generate a complete FastAPI inference script from a KiteML Result.

    Parameters
    ----------
    result : Result
    output_dir : str
        Directory to write the generated file. Default current dir.
    filename : str
        Output filename. Default ``'kiteml_api.py'``.

    Returns
    -------
    str
        Path to the generated file.
    """
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, filename)

    code = _APP_TEMPLATE.format(
        model_name=result.model_name,
        problem_type=result.problem_type,
        generated_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        model_name_repr=repr(result.model_name),
        problem_type_repr=repr(result.problem_type),
        feature_names_repr=repr(list(result.feature_names or [])),
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(code)

    print(f"⚙️  Generated API script → {out_path}")
    print(f"   Run with: uvicorn {filename[:-3]}:app --reload")
    return out_path
