"""
docker_export.py — Auto-generate Docker deployment files for KiteML models.

Generates a complete Docker deployment package:
  - Dockerfile
  - requirements.txt
  - serve.py (FastAPI inference server)
  - docker-compose.yml
  - .dockerignore

No Docker installation needed to generate these files.
"""

import os
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class DockerExportResult:
    """Result of docker export operation."""
    output_dir: str
    files_created: List[str]


_DOCKERFILE = """\
# ── KiteML Generated Dockerfile ──────────────────────────────────────────
# Auto-generated by KiteML. Do not edit manually unless you know what you do.
FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy model bundle and server
COPY . .

# Expose API port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD python -c "import requests; requests.get('http://localhost:{port}/health')" || exit 1

# Start server
CMD ["python", "serve.py"]
"""

_SERVE_PY = '''\
"""
serve.py — Auto-generated KiteML inference server.
Generated at: {generated_at}
Model: {model_name}
"""

import os
import time
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

import joblib
import numpy as np
import pandas as pd

try:
    from fastapi import FastAPI, HTTPException
    from fastapi.middleware.cors import CORSMiddleware
    from pydantic import BaseModel
except ImportError:
    raise ImportError("Install FastAPI: pip install fastapi uvicorn")

# ── Load artifacts ────────────────────────────────────────────────────────────
BUNDLE_DIR = os.path.dirname(os.path.abspath(__file__))
model = joblib.load(os.path.join(BUNDLE_DIR, "model.joblib"))
preprocessor = None
prep_path = os.path.join(BUNDLE_DIR, "preprocessor.joblib")
if os.path.exists(prep_path):
    preprocessor = joblib.load(prep_path)

import json
with open(os.path.join(BUNDLE_DIR, "metadata.json")) as f:
    metadata = json.load(f)

FEATURE_NAMES = metadata.get("feature_names", [])
PROBLEM_TYPE = metadata.get("problem_type", "classification")
MODEL_NAME = metadata.get("model_name", "Unknown")
START_TIME = time.time()
PREDICTION_COUNT = 0

# ── App setup ─────────────────────────────────────────────────────────────────
app = FastAPI(
    title=f"KiteML Model Server — {{MODEL_NAME}}",
    description="Auto-generated inference API by KiteML",
    version="1.0.0",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)

# ── Schemas ───────────────────────────────────────────────────────────────────
class PredictRequest(BaseModel):
    data: List[Dict[str, Any]]

class PredictResponse(BaseModel):
    predictions: List[Any]
    probabilities: Optional[List[Dict[str, float]]] = None
    latency_ms: float
    model_name: str

# ── Endpoints ─────────────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return {{"status": "ok", "uptime_s": round(time.time() - START_TIME, 1)}}

@app.get("/version")
def version():
    return metadata

@app.get("/schema")
def schema():
    return {{"features": FEATURE_NAMES, "problem_type": PROBLEM_TYPE}}

@app.get("/metrics")
def metrics():
    return {{"predictions_served": PREDICTION_COUNT, "uptime_s": round(time.time() - START_TIME, 1)}}

@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    global PREDICTION_COUNT
    t0 = time.perf_counter()
    try:
        df = pd.DataFrame(request.data)
        present = [f for f in FEATURE_NAMES if f in df.columns]
        df = df[present]
        X = preprocessor.transform(df) if preprocessor else df.values
        preds = model.predict(X).tolist()
        probas = None
        if PROBLEM_TYPE == "classification" and hasattr(model, "predict_proba"):
            raw = model.predict_proba(X)
            classes = [str(c) for c in getattr(model, "classes_", range(raw.shape[1]))]
            probas = [dict(zip(classes, [round(float(p), 4) for p in row])) for row in raw]
        PREDICTION_COUNT += len(preds)
        latency_ms = (time.perf_counter() - t0) * 1000
        return PredictResponse(predictions=preds, probabilities=probas,
                               latency_ms=round(latency_ms, 2), model_name=MODEL_NAME)
    except Exception as e:
        raise HTTPException(status_code=422, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port={port})
'''

_DOCKER_COMPOSE = """\
version: '3.8'
services:
  kiteml-model:
    build: .
    ports:
      - "{port}:{port}"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
"""

_DOCKERIGNORE = """\
__pycache__/
*.pyc
*.pyo
.git/
.pytest_cache/
*.egg-info/
dist/
build/
.env
"""


def export_docker(
    result: Any,
    output_dir: str,
    port: int = 8000,
    bundle_path: Optional[str] = None,
) -> DockerExportResult:
    """
    Generate a complete Docker deployment package.

    Parameters
    ----------
    result : Result
        Fitted KiteML result.
    output_dir : str
        Directory to write Docker files to.
    port : int
        Port for the inference server. Default 8000.
    bundle_path : str, optional
        If provided, also packages the .kiteml bundle into output_dir.

    Returns
    -------
    DockerExportResult
    """
    os.makedirs(output_dir, exist_ok=True)
    files_created: List[str] = []
    generated_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    # ── requirements.txt ──────────────────────────────────────────────────
    from kiteml.deployment.environment_capture import capture_environment
    env = capture_environment()

    # Minimal requirements for the inference server
    base_deps = [
        "scikit-learn>=1.3",
        "numpy>=1.24",
        "pandas>=2.0",
        "joblib>=1.3",
        "fastapi>=0.110",
        "uvicorn[standard]>=0.27",
        "pydantic>=2.0",
    ]
    req_path = os.path.join(output_dir, "requirements.txt")
    with open(req_path, "w", encoding="utf-8") as f:
        f.write(f"# KiteML inference server requirements\n# Generated: {generated_at}\n")
        f.write("\n".join(base_deps) + "\n")
    files_created.append(req_path)

    # ── Dockerfile ────────────────────────────────────────────────────────
    dockerfile_path = os.path.join(output_dir, "Dockerfile")
    with open(dockerfile_path, "w", encoding="utf-8") as f:
        f.write(_DOCKERFILE.format(port=port))
    files_created.append(dockerfile_path)

    # ── serve.py ──────────────────────────────────────────────────────────
    serve_path = os.path.join(output_dir, "serve.py")
    with open(serve_path, "w", encoding="utf-8") as f:
        f.write(_SERVE_PY.format(
            generated_at=generated_at,
            model_name=result.model_name,
            port=port,
        ))
    files_created.append(serve_path)

    # ── docker-compose.yml ────────────────────────────────────────────────
    compose_path = os.path.join(output_dir, "docker-compose.yml")
    with open(compose_path, "w", encoding="utf-8") as f:
        f.write(_DOCKER_COMPOSE.format(port=port))
    files_created.append(compose_path)

    # ── .dockerignore ─────────────────────────────────────────────────────
    ignore_path = os.path.join(output_dir, ".dockerignore")
    with open(ignore_path, "w", encoding="utf-8") as f:
        f.write(_DOCKERIGNORE)
    files_created.append(ignore_path)

    print(f"🐳 Docker deployment package generated → {output_dir}")
    print(f"   Files: {[os.path.basename(f) for f in files_created]}")
    print(f"   Build:  docker build -t kiteml-model {output_dir}")
    print(f"   Run:    docker run -p {port}:{port} kiteml-model")

    return DockerExportResult(output_dir=os.path.abspath(output_dir), files_created=files_created)
