"""
blueprint.py — Feature engineering blueprint models for KiteML.
"""

from dataclasses import asdict, dataclass, field
from typing import Any

from kiteml.feature_engineering.strategy import FETransformType


@dataclass
class EngineeredFeaturePlan:
    """
    Plan for a candidate engineered feature.
    """

    generated_name: str
    source_columns: list[str]
    transform_type: FETransformType | str
    provider_name: str
    confidence: float = 0.90
    reasoning: list[str] = field(default_factory=list)
    estimated_importance: float = 0.80  # 0.0 to 1.0 score
    enabled: bool = True

    def star_rating(self) -> str:
        """Render 5-star rating visual for estimated feature importance."""
        stars = min(5, max(1, round(self.estimated_importance * 5.0)))
        return "★" * stars + "☆" * (5 - stars)

    def to_dict(self) -> dict[str, Any]:
        """Serialize plan to dictionary."""
        d = asdict(self)
        tt = self.transform_type
        d["transform_type"] = tt.value if hasattr(tt, "value") else str(tt)
        d["star_rating"] = self.star_rating()
        return d


@dataclass
class FeatureEngineeringBlueprint:
    """
    Complete dataset feature engineering blueprint generated by FeatureEngineeringEngine.
    """

    feature_plans: dict[str, EngineeredFeaturePlan] = field(default_factory=dict)
    target_name: str | None = None
    problem_type: str | None = None
    skipped_count: int = 0
    warnings: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)

    @property
    def feature_count(self) -> int:
        """Total number of proposed engineered feature candidates."""
        return len(self.feature_plans)

    @property
    def enabled_features(self) -> list[str]:
        """Names of enabled candidate features."""
        return [f for f, p in self.feature_plans.items() if p.enabled]

    def summary_text(self, width: int = 55) -> str:
        """Render human-readable summary box of candidate feature engineering plan."""
        lines = [
            "═" * width,
            "⚙️ KiteML Feature Engineering Blueprint",
            "═" * width,
            f"  Target Column          {self.target_name or 'N/A'}",
            f"  Proposed Features      {self.feature_count}",
            f"  Enabled Candidates     {len(self.enabled_features)}",
            f"  Skipped Opportunities  {self.skipped_count}",
            "─" * width,
        ]

        for feat_name, plan in self.feature_plans.items():
            status = "✓" if plan.enabled else "❌"
            tt = plan.transform_type.value if hasattr(plan.transform_type, "value") else str(plan.transform_type)
            lines.append(f"  {status} {feat_name:<24} [{plan.star_rating()}] ({tt})")
            if plan.reasoning:
                lines.append(f"     → Reason: {plan.reasoning[0]}")

        lines.append("═" * width)
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """Serialize blueprint to dictionary."""
        return {
            "target_name": self.target_name,
            "problem_type": self.problem_type,
            "feature_count": self.feature_count,
            "enabled_count": len(self.enabled_features),
            "skipped_count": self.skipped_count,
            "feature_plans": {f: p.to_dict() for f, p in self.feature_plans.items()},
            "warnings": self.warnings,
            "suggestions": self.suggestions,
        }
