"""
KiteML Exception Framework Package.

Every KiteML error should teach the user how to fix the problem.
"""

from kiteml.exceptions.base import KiteMLError
from kiteml.exceptions.catalog import ErrorCatalog
from kiteml.exceptions.cli import CLIError
from kiteml.exceptions.codes import (
    KML_C001,
    KML_C002,
    KML_C003,
    KML_C004,
    KML_CFG001,
    KML_CFG002,
    KML_CFG003,
    KML_D001,
    KML_D002,
    KML_D003,
    KML_D004,
    KML_D005,
    KML_D006,
    KML_D007,
    KML_D008,
    KML_DP001,
    KML_DP002,
    KML_DP003,
    KML_DP004,
    KML_ERR_CLI,
    KML_ERR_CONFIG,
    KML_ERR_DATASET,
    KML_ERR_DEPLOYMENT,
    KML_ERR_GENERIC,
    KML_ERR_PREDICTION,
    KML_ERR_PREPROCESSING,
    KML_ERR_SCHEMA,
    KML_ERR_TARGET,
    KML_ERR_TRAINING,
    KML_ERR_VALIDATION,
    KML_I001,
    KML_I002,
    KML_I003,
    KML_I004,
    KML_M001,
    KML_M002,
    KML_M003,
    KML_M004,
    KML_P001,
    KML_P002,
    KML_P003,
    KML_P004,
    KML_S001,
    KML_S002,
    KML_S003,
    KML_S004,
    KML_S005,
    KML_S006,
    KML_S007,
    KML_S008,
    KML_T001,
    KML_T002,
    KML_T003,
    KML_T004,
    KML_T005,
    KML_T006,
    KML_T007,
    KML_V001,
    KML_V002,
    KML_V003,
    KML_V004,
)
from kiteml.exceptions.configuration import ConfigurationError
from kiteml.exceptions.context import ErrorContext
from kiteml.exceptions.dataset import DatasetError
from kiteml.exceptions.deployment import DeploymentError
from kiteml.exceptions.formatter import ErrorFormatter
from kiteml.exceptions.lookup import get_error_definition, lookup, search_errors
from kiteml.exceptions.metadata import ErrorDefinition
from kiteml.exceptions.prediction import PredictionError
from kiteml.exceptions.preprocessing import PreprocessingError
from kiteml.exceptions.registry import ErrorRegistry, global_error_registry
from kiteml.exceptions.renderer import (
    HtmlRenderer,
    JsonRenderer,
    MarkdownRenderer,
    TerminalRenderer,
    TextRenderer,
)
from kiteml.exceptions.schema import SchemaError
from kiteml.exceptions.target import TargetError
from kiteml.exceptions.templates import RenderModel, build_render_model
from kiteml.exceptions.themes import DEFAULT_THEME, Theme, get_theme
from kiteml.exceptions.training import TrainingError
from kiteml.exceptions.utils import build_dataframe_context, wrap_exception
from kiteml.exceptions.validation import ValidationError

__all__ = [
    "KiteMLError",
    "DatasetError",
    "TargetError",
    "SchemaError",
    "ValidationError",
    "PreprocessingError",
    "TrainingError",
    "DeploymentError",
    "PredictionError",
    "CLIError",
    "ConfigurationError",
    "ErrorContext",
    "ErrorDefinition",
    "ErrorCatalog",
    "ErrorRegistry",
    "global_error_registry",
    "lookup",
    "get_error_definition",
    "search_errors",
    "ErrorFormatter",
    "RenderModel",
    "build_render_model",
    "TerminalRenderer",
    "TextRenderer",
    "JsonRenderer",
    "HtmlRenderer",
    "MarkdownRenderer",
    "Theme",
    "DEFAULT_THEME",
    "get_theme",
    "KML_ERR_GENERIC",
    "KML_ERR_DATASET",
    "KML_ERR_TARGET",
    "KML_ERR_SCHEMA",
    "KML_ERR_VALIDATION",
    "KML_ERR_PREPROCESSING",
    "KML_ERR_TRAINING",
    "KML_ERR_DEPLOYMENT",
    "KML_ERR_PREDICTION",
    "KML_ERR_CLI",
    "KML_ERR_CONFIG",
    "KML_D001",
    "KML_D002",
    "KML_D003",
    "KML_D004",
    "KML_D005",
    "KML_D006",
    "KML_D007",
    "KML_D008",
    "KML_T001",
    "KML_T002",
    "KML_T003",
    "KML_T004",
    "KML_T005",
    "KML_T006",
    "KML_T007",
    "KML_S001",
    "KML_S002",
    "KML_S003",
    "KML_S004",
    "KML_S005",
    "KML_S006",
    "KML_S007",
    "KML_S008",
    "KML_V001",
    "KML_V002",
    "KML_V003",
    "KML_V004",
    "KML_P001",
    "KML_P002",
    "KML_P003",
    "KML_P004",
    "KML_M001",
    "KML_M002",
    "KML_M003",
    "KML_M004",
    "KML_I001",
    "KML_I002",
    "KML_I003",
    "KML_I004",
    "KML_DP001",
    "KML_DP002",
    "KML_DP003",
    "KML_DP004",
    "KML_C001",
    "KML_C002",
    "KML_C003",
    "KML_C004",
    "KML_CFG001",
    "KML_CFG002",
    "KML_CFG003",
    "build_dataframe_context",
    "wrap_exception",
]
